### ISSUE TITLE
Stdout includes print statements when rendering image

### ISSUE THREAD

**Issue by 7webfrog** [DouweM/tap-pixlet#7]
Specifically looking at the code here: https://github.com/DouweM/tap-pixlet/blob/d7a67dfc84d0de0efcd155263827301c18b6ba38/tap_pixlet/streams.py#L231

My `.star` file includes print statements, so when `pixlet render` runs, the results of those print statements as well as the rendered image are in `stdout`. When it tries to push the image to Tidbyt, I get this response:
`{"code":2,"message":"image.DecodeConfig: image: unknown format","details":[]}`

I decoded the image from base64 and confirmed that it has my print statements followed by the rendered image.

To replicate, run a `.star` file with print statements in terminal with this command:
`pixlet render <app>.star -m 1 -o -` where `<app>` is app name

**Comment by DouweM** [comment]
@7webfrog Thanks for the report! This feels to me like incorrect behavior in Pixlet: if we're saying "output as WebP on stdout" with `-o -`, I'd expect stdout to only get the WebP output and for print statements to go to stderr.

We could work around this by writing the image to a temporary file instead of stdout, and then reading the image data from the file and treating the stdout text as debug output to bubble up for your convenience.

**Comment by DouweM** [comment]
@7webfrog This should be fixed in the latest tap-pixlet! You can install it by running `meltano install --clean` in your Pixbyt directory, or if you're building a Docker image, you can pin `tap-pixlet` in `plugins/plugins.meltano.yml` by adding `@<commit id>` at the end of the `pip_url` and commit the change to force a rebuild.
